create type if not exists roles as enum ('Посетитель','Боцман','Матрос','Повар','Капитан','Администратор');
create type  if not exists status_travel as enum ('Заполнено', 'Идет набор команды', 'В отплыве', 'Закончено', 'Открыто для набора посетителей','Отменено');
create type  if not exists state as enum ('Одобрено', 'Отказано', 'В ожидании');
create type   if not exists status_invite as enum('Принял','Отказал','Не ответил');
create  type  if not exists status_ship as enum ('Свободен','Зарезервирован');

create table if not exists Users(
        ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name varchar(50) not null,
        role roles not null,
        nickname varchar (250) unique,
        password text not null,
        surname varchar(50) not null,
        middle_name varchar(50) not null
);
create  table if not exists Ship(
        ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        status status_ship not null,
        name varchar(50) not null ,
        description text not null,
        url text not null,
        count_places int not null
);
create table if not exists  Travel(
        ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name varchar(250) not null ,
        ship_id BIGINT references Ship(id),
        status status_travel not null,
        description text not null,
        date_start date not null,
        date_end date not null
);
create  table if not exists  Invitation(
        ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        travel_id BIGINT references  Travel(ID),
        user_id BIGINT references  Users(ID),
        status status_invite not null
);
create table  if not exists  Crew(
        ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        travel_id BIGINT references  Travel(ID),
        user_id BIGINT references  Users(ID)
);
create table if not exists Bid (
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT references Users(id),
    role roles not null ,
    description text not null,
    status state not null
);
create table Team_Visitor(
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    travel_id BIGINT references  Travel(ID),
    user_id BIGINT references Users(id)
);
